---
- name:  Deleting the user sysadmin on all nodes
  hosts: all
  become: true
  become_user: root
  vars:
    sysadmin_password: redhat
  tasks:
  - name : Deleting user ...
    user:
      name: sysadmin
      comment: Muhammad ALi
      password: "{{ sysadmin_password | password_hash('sha512', 'mysecretsalt') }}"
      state: absent
